# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/AyusSalleh/WAActionSheetControllerPodSpecs.git'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
    pod 'WAActionSheetController', :modular_headers => true

  target 'ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
